[package]
name = "token_transfer"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.2.1"
solana-program = "1.17.6"
spl-token = "4.0"

[dev-dependencies]
solana-program-test = "1.17.6"
solana-sdk = "1.17.6"

[lib]
crate-type = ["cdylib", "lib"]